package com.gocar.app.enums;

import lombok.Getter;

@Getter
public enum Feature {

    AIR_CONDITIONING("AIR_CONDITIONING"),
    AUTOMATIC_TRANSMISSION("AUTOMATIC_TRANSMISSION"),
    FM_RADIO("FM_RADIO"),
    CENTRAL_LOCKING("CENTRAL_LOCKING"),
    POWER_WINDOWS("POWER_WINDOWS"),
    POWER_MIRRORS("POWER_MIRRORS"),
    AIRBAGS("AIRBAGS"),
    ABS_BRAKES("ABS_BRAKES"),
    NAVIGATION_SYSTEM("NAVIGATION_SYSTEM"),
    BLUETOOTH("BLUETOOTH"),
    USB_PORT("USB_PORT"),
    REARVIEW_CAMARA("REARVIEW_CAMARA"),
    SUNROOF("SUNROOF"),
    LEATHER_SEATS("LEATHER_SEATS"),
    CRUISE_CONTROL("CRUISE_CONTROL"),
    COLLISION_MITIGATION_SYSTEM("COLLISION_MITIGATION_SYSTEM"),
    ANDROID_AUTO("ANDROID_AUTO"),
    PARKING_SENSORS("PARKING_SENSORS");


    private final String description;

    Feature(String description){
        this.description=description;
    }

}
